import { configureStore } from "@reduxjs/toolkit";
import {
  UserMetadataReducer,
  UserKeysReducer,
  UserBookmarksReducer,
  UserRelaysReducer,
  UserChatroomsReducer,
  UserChatContactsReducer,
  UserFollowingsReducer,
  UserMutedListReducer,
  UserBalanceReducer,
  UserFollowingsRelaysReducer,
  WalletsReducer,
  SelectedWalletReducer,
  UserAllRelaysReducer,
  UserInterestListReducer,
  UserSavedToolsReducer,
  UserAppSettingsReducer,
} from "./Slides/UserData";
import {
  UserFirstLoginYakiChestReducer,
  IsConnectedToYakiReducer,
  YakiChestStatsReducer,
  IsYakiChestLoadedReducer,
  UpdatedActionFromYakiChestSliceReducer,
} from "./Slides/YakiChest";
import { NostrAuthorsReducer, NostrClientsReducer } from "./Slides/Profiles";
import {
  ToastReducer,
  ToPublishReducer,
  IsPublishingReducer,
} from "./Slides/Publishers";
import {
  IsDarkModeReducer,
  InitDMSReducer,
  FollowersCountSLReducer,
  ImportantFlashNewsReducer,
  TrendingUsersReducer,
  RecentTagsReducer,
} from "./Slides/Extras";

export const store = configureStore({
  reducer: {
    userMetadata: UserMetadataReducer,
    userKeys: UserKeysReducer,
    userBookmarks: UserBookmarksReducer,
    userRelays: UserRelaysReducer,
    userInterestList: UserInterestListReducer,
    userAllRelays: UserAllRelaysReducer,
    userChatrooms: UserChatroomsReducer,
    userChatContacts: UserChatContactsReducer,
    userFollowings: UserFollowingsReducer,
    userMutedList: UserMutedListReducer,
    userBalance: UserBalanceReducer,
    userFirstLoginYakiChest: UserFirstLoginYakiChestReducer,
    userSavedTools: UserSavedToolsReducer,
    userAppSettings: UserAppSettingsReducer,
    isConnectedToYaki: IsConnectedToYakiReducer,
    yakiChestStats: YakiChestStatsReducer,
    isYakiChestLoaded: IsYakiChestLoadedReducer,
    nostrAuthors: NostrAuthorsReducer,
    nostrClients: NostrClientsReducer,
    toast: ToastReducer,
    toPublish: ToPublishReducer,
    isPublishing: IsPublishingReducer,
    isDarkMode: IsDarkModeReducer,
    initDMS: InitDMSReducer,
    followersCountSL: FollowersCountSLReducer,
    updatedActionFromYakiChest: UpdatedActionFromYakiChestSliceReducer,
    userFollowingsRelays: UserFollowingsRelaysReducer,
    importantFlashNews: ImportantFlashNewsReducer,
    trendingUsers: TrendingUsersReducer,
    recentTags: RecentTagsReducer,
    wallets: WalletsReducer,
    selectedWallet: SelectedWalletReducer,
  },
});
